ALTER TABLE "Session"
ADD COLUMN "lastActiveAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE "Session"
SET "lastActiveAt" = COALESCE("createdAt", CURRENT_TIMESTAMP)
WHERE "lastActiveAt" IS NULL;
